apiVersion: v1
kind: Service
metadata:
  name: jkeweb
  labels:
    app: jke
    tier: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9080
    nodePort: 31980
  selector:
    app: jke
    tier: frontend

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jkeweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jke
        tier: frontend
    spec:
      containers:
      - name: jkeweb
        image: mycluster.icp:8500/default/websphere-liberty:webProfile8  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: wars
          mountPath: /config/dropins
      volumes:
      - name: wars
        persistentVolumeClaim:
          claimName: wars-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jkedb
  labels:
    app: jke
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 32306
  selector:
    app: jke
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jkedb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jke
        tier: backend
    spec:
      containers:
      - name: jkedb
        image: mycluster.icp:8500/default/jke.db:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
